export const CHANGE_DEPARTURE_FIELD = 'CHANGE_DEPARTURE_FIELD';
export const CHANGE_ARRIVAL_FIELD = 'CHANGE_ARRIVAL_FIELD';
export const CHANGE_DEPARTURE_DATE_FIELD = 'CHANGE_DEPARTURE_DATE_FIELD';
export const CHANGE_ARRIVAL_DATE_FIELD = 'CHANGE_ARRIVAL_DATE_FIELD';
export const CHANGE_FOOTER_FIELD = 'CHANGE_FOOTER_FIELD';