export const CHANGE_DEPARTURE_FIELD = 'CHANGE_DEPARTURE_FIELD';
export const CHANGE_ARRIVAL_FIELD = 'CHANGE_ARRIVAL_FIELD';
export const CHANGE_DEPARTURE_DATE_FIELD = 'CHANGE_DEPARTURE_DATE_FIELD';
export const CHANGE_ARRIVAL_DATE_FIELD = 'CHANGE_ARRIVAL_DATE_FIELD';
export const CHANGE_FOOTER_FIELD = 'CHANGE_FOOTER_FIELD';

export const GET_LAST_ROUTES_REQUEST = 'GET_LAST_ROUTES_REQUEST';
export const GET_LAST_ROUTES_FAILURE = 'GET_LAST_ROUTES_FAILURE';
export const GET_LAST_ROUTES_SUCCESS = 'GET_LAST_ROUTES_SUCCESS';